basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: API untuk manajemen pencari kerja dan lowongan pekerjaan.
  title: JobSeeker API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: Masukkan token dalam format "Bearer <token>"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
